sudo: required

language: go
go: 1.13.x

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/modocache/gover
  # Required by Kubernetes 1.18
  - sudo apt-get install -y conntrack
  - make setup/travis

install: make test/e2e-local-image NAMESPACE=default

after_failure:
  - echo "---- Keycloak Server logs ----"
  - kubectl logs keycloak-0
  - echo "---- Testing Ingress ----"
  - curl -kv https://keycloak.local/auth
  - echo "---- Ingress Controller logs ----"
  - kubectl logs -l app.kubernetes.io/name=nginx-ingress-controller -n kube-system