apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: example-keycloakrealm
  labels:
    app: sso
spec:
  realm:
    id: events-realm
    realm: events-realm
    enabled: True
    displayName: Events Realm
    adminEventsEnabled: True
    eventsEnabled: True
    eventsListeners:
      - jboss-logging
    enabledEventTypes:
      - SEND_RESET_PASSWORD
      - UPDATE_CONSENT_ERROR
      - GRANT_CONSENT
      - REMOVE_TOTP
      - REVOKE_GRANT
      - UPDATE_TOTP
      - LOGIN_ERROR
      - CLIENT_LOGIN
      - RESET_PASSWORD_ERROR
      - IMPERSONATE_ERROR
      - CODE_TO_TOKEN_ERROR
      - CUSTOM_REQUIRED_ACTION
      - RESTART_AUTHENTICATION
      - IMPERSONATE
      - UPDATE_PROFILE_ERROR
      - LOGIN
      - UPDATE_PASSWORD_ERROR
      - CLIENT_INITIATED_ACCOUNT_LINKING
      - TOKEN_EXCHANGE
      - LOGOUT
      - REGISTER
      - DELETE_ACCOUNT_ERROR
      - CLIENT_REGISTER
      - IDENTITY_PROVIDER_LINK_ACCOUNT
      - DELETE_ACCOUNT
      - UPDATE_PASSWORD
      - CLIENT_DELETE
      - FEDERATED_IDENTITY_LINK_ERROR
      - IDENTITY_PROVIDER_FIRST_LOGIN
      - CLIENT_DELETE_ERROR
      - VERIFY_EMAIL
      - CLIENT_LOGIN_ERROR
      - RESTART_AUTHENTICATION_ERROR
      - EXECUTE_ACTIONS
      - REMOVE_FEDERATED_IDENTITY_ERROR
      - TOKEN_EXCHANGE_ERROR
      - PERMISSION_TOKEN
      - SEND_IDENTITY_PROVIDER_LINK_ERROR
      - EXECUTE_ACTION_TOKEN_ERROR
      - SEND_VERIFY_EMAIL
      - EXECUTE_ACTIONS_ERROR
      - REMOVE_FEDERATED_IDENTITY
      - IDENTITY_PROVIDER_POST_LOGIN
      - IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR
      - UPDATE_EMAIL
      - REGISTER_ERROR
      - REVOKE_GRANT_ERROR
      - EXECUTE_ACTION_TOKEN
      - LOGOUT_ERROR
      - UPDATE_EMAIL_ERROR
      - CLIENT_UPDATE_ERROR
      - UPDATE_PROFILE
      - CLIENT_REGISTER_ERROR
      - FEDERATED_IDENTITY_LINK
      - SEND_IDENTITY_PROVIDER_LINK
      - SEND_VERIFY_EMAIL_ERROR
      - RESET_PASSWORD
      - CLIENT_INITIATED_ACCOUNT_LINKING_ERROR
      - UPDATE_CONSENT
      - REMOVE_TOTP_ERROR
      - VERIFY_EMAIL_ERROR
      - SEND_RESET_PASSWORD_ERROR
      - CLIENT_UPDATE
      - CUSTOM_REQUIRED_ACTION_ERROR
      - IDENTITY_PROVIDER_POST_LOGIN_ERROR
      - UPDATE_TOTP_ERROR
      - CODE_TO_TOKEN
      - GRANT_CONSENT_ERROR
      - IDENTITY_PROVIDER_FIRST_LOGIN_ERROR
  instanceSelector:
    matchLabels:
      app: sso