name: CI
on: [push, pull_request]
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go
    - name: Install dependencies
      run: |
        go get github.com/mattn/goveralls
        go get github.com/modocache/gover
        sudo apt-get install -y conntrack
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Unit tests
      run: |
        make test/unit
    - name: Start minikube
      uses: manusa/actions-setup-minikube@v2.3.1
      with:
        minikube version: 'v1.16.0'
        kubernetes version: 'v1.19.2'
        driver: 'docker'
    - name: Configure Minikube
      run: |
        minikube addons enable ingress
        hack/modify_etc_hosts.sh "keycloak.local"
    - name: Run e2e tests
      run: |
        make cluster/prepare
        make test/e2e
        make cluster/clean
    - name: Run e2e tests for local image
      run: |
        make test/e2e-local-image
